### PR TITLE
Base classes for a Spotify API

### PR DESCRIPTION
**Pull request by kdschlosser**
DO NOT MERGE THIS!!!!!

This is a WIP. But what I am doing here is I am creating an API to
connect with Spotify. I have made a storage container or class for each
of the data sets that Spotify returns. I have made them in such a way
that the data will not get loaded into it's container until it is used
once used it will be cached so it doesn't have to go through conversion
again. I am going to make it so that not a single item would have to be
remade by using the id of the item it will check to see if it already
exists and if it does to return the existing item instead of generating
a new one. This becomes useful for 2 reasons. 1: Speed, 2: Access to the
same items between modules. So for example if i delete a track in
module A it is also deleted in module B without the need to tell
module B directly that it has been deleted.

### CODE REVIEW

**Comment by kdschlosser** [comment]
I added an automatic router discovery and upnp setting of the port to be forwarded for the callback/redirect url. and also a way to remove the port forward when the program ends.

**Review by RonnyAL — COMMENTED** [review]
That's cool! However, the user would have to specify a certain port when setting up their web app (unless we are gonna create a web app that will manage all users, but I think we may struggle with rate limits in tha case). Not saying your idea is incompatible with this, but I'm not 100% certain it is. Let me know if I'm wrong. :)

**Comment by kdschlosser** [comment]
heh... the way this thing works is. we will give the user the ability to set up a custom host name and/or port if they like. so what will happen is. they will click on a button to set the router crap into motion. if they didn't specify a host or a port it will kick back the external IP with a random port. and this we can store and pass into it when it goes to connect the next time around. But it will display the uri that will need to be entered into Spotify if they haven't already done so.

and ya lost me as far as the all users and the rate limit. I know there is a rate limit i have not done much poking into it. But because of the way my API is set up it is going to cache the data so it will not have to make a crap load of repeated calls. so as an example. if you view a specific album. and then you go and view it again 2 minutes later it will not make a call to Spotify again. this was the downside of all of the API's that i have seen that are currently made. I do plan on setting into place a refresh of the data during idle times. to make sure you didn't login elsewhere and make changes.

**Comment by RonnyAL** [comment]
I see! Regarding the default external IP, what would happen when it changes (as it does for most people)? I'm sure the plugin could detect and react to that, but how about the Spotify Web App (that would now need a new redirect URL on its list of allowed ones)?

The caching part is very interesting. I see it being a huge benefit when it comes to selecting a playlist for that "Add current song to playlist" function. We could easily have a drop-down menu with all the users playlists. For some of the other API calls I don't see any obvious use cases. For example, why would one automate looking up a specific album, and what kind of GUI would one use for that?

Finally, as for rate limits it seems like the specifics aren't publicly available. We would still have a significantly higher probability of hitting them however if every user was tied to the same web app. We'd also have that problem regarding allowed redirect URLs (mentioned above). So in my humble opinion it's best that users create their own web apps.

All in all, I'm very impressed by your thoroughness and don't mean to criticize. Just trying to help you figure out what this plugin should (and shouldn't) be. It's all very exciting to be a part of, in any case!

**Pull request closed without merging**
